(()=>{
 const config=JSON.parse(document.getElementById('limb-config').textContent),region=config.region,prefix=region,root=document.getElementById(region+'-motion'),by=id=>document.getElementById(prefix+'-'+id),hub=document.getElementById('hub-config'),hubConfig=hub?JSON.parse(hub.textContent):null,store=config.store,topic=config.topic,views=config.views||['front','side','back'];
 const model=NativeLimbRenderer(root,JSON.parse(document.getElementById('limb-atlas').textContent),region,JSON.parse(document.getElementById('limb-reference').textContent),JSON.parse(document.getElementById('limb-bone-fields').textContent));
 let angle=config.initial,view='front',playing=false,phase=0,last=0,lastDraw=0,lastCapture=0;
 let saved=hubConfig?.state;try{saved??=JSON.parse(localStorage.getItem(store)||'null');}catch{}const content=saved?.modelContent;if(content?.topic===topic){if(Number.isFinite(content.angle))angle=Math.max(config.min,Math.min(config.max,content.angle));if(views.includes(content.camera))view=content.camera;if(typeof content.fibers==='boolean')by('fibers').checked=content.fibers;if(typeof content.transparent==='boolean')by('transparent').checked=content.transparent;playing=saved.privateContent?.playing===true&&!matchMedia('(prefers-reduced-motion: reduce)').matches;}
 function render(){if(!root.isConnected)return;root.classList.toggle('no-fibers',!by('fibers').checked);root.classList.toggle('transparent',by('transparent').checked);root.dataset.revision='native-limb-atlas-v1';root.dataset.angle=Math.round(angle);root.dataset.camera=view;model.render(angle,view);by('angle').value=Math.round(angle);const text=region==='forearm'?(Math.round(angle)===0?'중립 0°':(angle<0?'회외 ':'회내 ')+Math.abs(Math.round(angle))+'°'):(Math.round(angle)===0?'펴짐 0°':'굽힘 '+Math.round(angle)+'°');by('value').textContent=text;by('angle').setAttribute('aria-valuetext',text);for(const v of views)by(v).setAttribute('aria-pressed',v===view);by('view-caption').textContent=(view==='medial'?'측면(반대) · 허벅지 안쪽':view==='side'?'측면':view==='front'?'정면'+(region==='thigh'?' 사선':''):'후면'+(region==='thigh'?' 사선':''))+' · '+(region==='forearm'?'오른팔 · 회내·회외':'오른쪽 허벅지 · 무릎 굽힘');}
 function capture(){const state={modelContent:{revision:'native-limb-atlas-v1',topic,angle:Math.round(angle),camera:view,fibers:by('fibers').checked,transparent:by('transparent').checked},privateContent:{playing}};try{localStorage.setItem(store,JSON.stringify(state));}catch{}if(hubConfig)parent.postMessage({type:'anatomy-hub-state',key:hubConfig.key,state},'*');}
 function play(on){playing=on;by('play').textContent=on?'일시정지':'재생';by('play').setAttribute('aria-pressed',on);last=0;}
 function syncPhase(){phase=Math.acos(Math.max(-1,Math.min(1,1-2*(angle-config.min)/(config.max-config.min))));}
 by('angle').addEventListener('input',()=>{play(false);angle=+by('angle').value;render();capture();});by('play').addEventListener('click',()=>{if(!playing)syncPhase();play(!playing);capture();});for(const v of views)by(v).addEventListener('click',()=>{view=v;render();capture();queueFit();});for(const id of ['fibers','transparent'])by(id).addEventListener('change',()=>{render();capture();queueFit();});
 let pending=false;function fit(){pending=false;if(!root.isConnected)return;const svg=root.querySelector('svg'),available=Math.max(0,document.documentElement.clientWidth-32),overhead=root.scrollHeight-svg.getBoundingClientRect().height,width=Math.floor(available<=680?available:Math.min(available,700,Math.max(220,(innerHeight-overhead-48)*600/630)))+'px';if(root.style.width!==width)root.style.width=width;}
 function queueFit(){if(!pending){pending=true;requestAnimationFrame(fit);}}window.addEventListener('resize',queueFit);new ResizeObserver(queueFit).observe(root);new ResizeObserver(render).observe(root);
 function tick(t){if(!root.isConnected)return;if(playing&&!document.hidden&&t-lastDraw>=85){if(last)phase+=Math.min(t-last,160)*Math.PI/5500;angle=config.min+(config.max-config.min)*(1-Math.cos(phase))/2;render();last=t;lastDraw=t;if(t-lastCapture>=500){capture();lastCapture=t;}}requestAnimationFrame(tick);}requestAnimationFrame(tick);
 window.nativeLimb={model,root,setPose(a,v=view){play(false);angle=Math.max(config.min,Math.min(config.max,a));if(views.includes(v))view=v;render();capture();}};syncPhase();play(playing);render();queueFit();capture();
})();
