function NativeLimbRenderer(root,model,region,reference,fields){
 const composition=AnatomyComposition(root,model.parts,region);
 const motion=NativeLimbMotion(model,region,reference),collision=NativeLimbCollision(fields,motion),svg=root.querySelector('svg'),ns='http://www.w3.org/2000/svg';
 const make=(tag,attrs,parent)=>{const n=document.createElementNS(ns,tag);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,v));parent.append(n);return n;};
 const defs=svg.querySelector('defs'),drawing=svg.querySelector('.native-volumes'),labels=svg.querySelector('.native-labels');
 const parts=model.parts.flatMap(p=>{if(!p.tendonFaces?.length)return[p];const ts=new Set(p.tendonFaces);return[{...p,f:p.f.filter((_,i)=>!ts.has(i))},{...p,f:p.f.filter((_,i)=>ts.has(i)),name:p.name+'-tendon-material',material:'tendon'}];});
 const labelNames={'brachioradialis':'상완요골근','flexor-carpi-radialis':'요측수근굴근','flexor-carpi-ulnaris-humeral':'척측수근굴근 상완두','flexor-carpi-ulnaris-ulnar':'척측수근굴근 척골두','flexor-digitorum-superficialis-humeroulnar':'천지굴근 상완척골두','flexor-digitorum-superficialis-radial':'천지굴근 요골두','flexor-digitorum-profundus':'심지굴근','palmaris-longus':'장장근','extensor-carpi-radialis-longus':'장요측수근신근','extensor-carpi-radialis-brevis':'단요측수근신근','extensor-digitorum':'총지신근','extensor-carpi-ulnaris-humeral':'척측수근신근 상완두','extensor-carpi-ulnaris-ulnar':'척측수근신근 척골두','pronator-teres-humeral':'원회내근 상완두','pronator-teres-ulnar':'원회내근 척골두','supinator':'회외근','pronator-quadratus':'방형회내근','rectus-femoris':'대퇴직근','vastus-lateralis':'외측광근','vastus-medialis':'내측광근','vastus-intermedius':'중간광근','biceps-femoris-long':'대퇴이두근 장두','biceps-femoris-short':'대퇴이두근 단두','semitendinosus':'반힘줄근','semimembranosus':'반막근','sartorius':'봉공근','adductor-longus':'내전근'};
 const nodes=parts.map((part,id)=>{const g=make('g',{'data-muscle':part.kind==='muscle'?part.name:'','data-part':part.name,'data-kind':part.kind},drawing),clip=make('clipPath',{id:region+'-native-clip-'+id},defs),mask=make('path',{},clip),fill=make('path',{fill:part.kind==='bone'?'#e8e9eb':part.material==='tendon'?'#fafafa':part.kind==='muscle'?'color-mix(in srgb,'+(part.displayColor||'#edb0a7')+' 85%,white)':part.displayColor||'#edb0a7'},g),outline=make('path',{fill:'none',stroke:'var(--muted-foreground)','stroke-width':part.kind==='bone'?.9:.55,'stroke-opacity':part.kind==='muscle'&&!part.material?.22:.5},g),fiber=make('path',{class:'fiber',fill:'none',stroke:'var(--foreground)','stroke-width':.55,'stroke-opacity':part.material==='tendon'?.18:.28,'clip-path':'url(#'+region+'-native-clip-'+id+')'},g);return{part,g,mask,fill,outline,fiber};});
 composition.mountFat(make,drawing);
 const groupName=name=>region==='thigh'?(name.startsWith('biceps-femoris-')?'biceps-femoris':name):name==='brachioradialis'?name:name.startsWith('flexor')||name==='palmaris-longus'?'flexors':name.startsWith('extensor')?'extensors':name.startsWith('pronator')?'pronators':name;
 Object.assign(labelNames,{flexors:'굽힘근군',extensors:'폄근군',pronators:'회내근군','biceps-femoris':'대퇴이두근'});
 const labelNodes=new Map();for(const p of model.parts.filter(p=>p.kind==='muscle')){if(labelNodes.has(groupName(p.name)))continue;const g=make('g',{'data-label':p.name},labels),line=make('path',{},g),text=make('text',{},g);text.textContent=labelNames[groupName(p.name)];labelNodes.set(groupName(p.name),{g,line,text});}
 const v=model.parts.flatMap(p=>p.v),lo=Math.min(...v.map(p=>p[1])),hi=Math.max(...v.map(p=>p[1])),scale=565/(hi-lo),cx=v.reduce((s,p)=>s+p[0]/v.length,0),cz=v.reduce((s,p)=>s+p[2]/v.length,0),cache=new Map();let lastKey='',debug=null;
 const lightSurfaces=AnatomySurfaceLighting(make,nodes.flatMap((n,id)=>n.part.kind==='muscle'&&!n.part.material?[{owner:id,g:n.g,clip:n.fiber.getAttribute('clip-path'),anchor:n.outline,fill:n.fill}]:[]),{depthScale:scale});
 const curve=ps=>{if(ps.length<3)return '';let d='M'+ps[0].join(',');for(let i=1;i<ps.length-1;i++)d+='Q'+ps[i].join(',')+' '+ps[i].map((v,j)=>(v+ps[i+1][j])/2).join(',');return d+'L'+ps.at(-1).join(',');};
 function pose(angle){const key=angle+':'+composition.key;if(cache.has(key))return cache.get(key);const raw=model.parts.map(p=>({p,v:p.v.map(q=>{const v=motion.deform(composition.point(p,q),p,angle);return p.kind==='bone'?v:collision.constrain(v,angle);})})),byName=new Map(raw.map(x=>[x.p.name,x.v])),result=nodes.map(n=>byName.get(n.part.name.replace(/-tendon-material$/,'')));cache.set(key,result);if(cache.size>3)cache.delete(cache.keys().next().value);return result;}
 function render(angle,view){angle=Math.round(angle);const transparent=root.classList.contains('transparent'),fibers=!root.classList.contains('no-fibers'),key=[angle,view,transparent,fibers,root.clientWidth,composition.key].join();if(key===lastKey)return;lastKey=key;const start=performance.now(),posed=pose(angle),yaw=model.pose.cameraYawByView?.[view]??model.pose.cameraYaw[['front','side','back'].indexOf(view)],a=yaw*Math.PI/180,c=Math.cos(a),s=Math.sin(a),project=p=>[300+((p[0]-cx)*c+(p[2]-cz)*s)*scale,20+(p[1]-lo)*scale],depth=p=>-p[0]*s+p[2]*c;
  const buffer=AbdominalVisibility({project,depth,step:1});nodes.forEach((n,id)=>n.part.f.forEach(f=>buffer.polygon(f.map(j=>posed[id][j]),id)));const byName=new Map(nodes.map((n,id)=>[n.part.name,posed[id]])),fatCount=composition.paintFat(buffer,model.parts.map(p=>byName.get(p.name)),nodes.length);
  const visible=buffer.solve(nodes.length+fatCount,{projections:id=>id>=nodes.length||nodes[id].part.kind!=='bone',scanlineClips:false,occludes:id=>id>=nodes.length?!composition.fatTransparent:!transparent||nodes[id].part.kind==='bone'});
  nodes.forEach((n,id)=>{const soft=n.part.kind!=='bone',local=visible.ownerZ[id],contour=AtlasContour(visible,k=>transparent&&soft?local[k]>-Infinity:visible.owners[k]===id,visible.bounds[id]);for(const el of [n.fill,n.outline,n.mask])el.setAttribute('d',contour);n.g.setAttribute('opacity',transparent&&soft?.3:1);let path='';
   if(fibers)for(const fiber of n.part.fibers){let segment=[];const flush=()=>{let length=0;for(let j=1;j<segment.length;j++)length+=Math.hypot(...segment[j].map((v,k)=>v-segment[j-1][k]));if(length>=5)path+=curve(segment);segment=[];};for(const p of fiber){const point=collision.constrain(motion.deform(composition.point(n.part,p),n.part,angle),angle),q=project(point),x=Math.floor((q[0]-visible.x0)/visible.step),y=Math.floor((q[1]-visible.y0)/visible.step),k=y*visible.w+x;if(x>=0&&x<visible.w&&y>=0&&y<visible.h&&depth(point)>=local[k]-2&&(transparent||visible.owners[k]===id))segment.push(q);else flush();}flush();}n.fiber.setAttribute('d',path);
  });
  lightSurfaces(visible);
  composition.drawFat(visible,nodes.length,AtlasContour);
  labelNodes.forEach(n=>n.g.style.display='none');const shown=[];
  nodes.forEach((n,id)=>{if(n.part.kind!=='muscle'||n.part.material)return;let points=visible.centers[id];if(transparent){points=[];const local=visible.ownerZ[id],b=visible.bounds[id];for(let y=b[1];y<=b[3];y+=8)for(let x=b[0];x<=b[2];x+=8)if(local[y*visible.w+x]>-Infinity)points.push([visible.x0+(x+.5)*visible.step,visible.y0+(y+.5)*visible.step]);}if(points.length<3||!transparent&&visible.coverage[id]<100)return;
   const avg=points.reduce((sum,p)=>sum.map((v,j)=>v+p[j]/points.length),[0,0]),target=points.reduce((best,p)=>Math.hypot(...p.map((v,j)=>v-avg[j]))<Math.hypot(...best.map((v,j)=>v-avg[j]))?p:best);const name=groupName(n.part.name),existing=shown.find(item=>groupName(item.n.part.name)===name);if(!existing)shown.push({n,id,target,coverage:visible.coverage[id]});else if(visible.coverage[id]>existing.coverage)Object.assign(existing,{n,id,target,coverage:visible.coverage[id]});
  });
  // Fixed side columns sorted by the actual visible attachment target.
  shown.sort((a,b)=>a.target[1]-b.target[1]);let left=0,right=0;for(const item of shown){const l=item.target[0]<300,slot=l?left++:right++,x=l?12:588,y=75+slot*46,label=labelNodes.get(groupName(item.n.part.name));label.g.style.display='';label.text.setAttribute('x',x);label.text.setAttribute('y',y);label.text.setAttribute('text-anchor',l?'start':'end');label.line.setAttribute('d',`M${x},${y+5}L${item.target.join(',')}`);}
  const legend=root.querySelector('.native-legend');legend.replaceChildren();for(const item of shown){const span=document.createElement('span'),key=document.createElement('i');key.style.background=item.n.part.displayColor;span.append(key,document.createTextNode(labelNames[groupName(item.n.part.name)]));legend.append(span);}
  svg.setAttribute('viewBox','0 0 600 630');svg.style.height='auto';labelNodes.forEach(n=>n.text.style.fontSize=(11*600/Math.max(1,root.clientWidth))+'px');root.dataset.cameraYaw=yaw;debug={angle,view,coverage:visible.coverage,duration:performance.now()-start,metrics:motion.metrics(angle),posed:posed.map((v,id)=>({name:nodes[id].part.name,kind:nodes[id].part.kind,v}))};
 }
 return{render,motion,collision,model,nodes,composition,get debug(){return debug;}};
}
