(()=>{
 const config={region:'upperbody',store:'artist-upperbody-v1',topic:'상체 팔 올리기',initial:60,min:15,max:120},region=config.region,prefix=region,root=document.getElementById(region),by=id=>document.getElementById(prefix+'-'+id),hub=document.getElementById('hub-config'),hubConfig=hub?JSON.parse(hub.textContent):null,store=config.store,topic=config.topic;
 const model=NativeUpperbodyRenderer(root,JSON.parse(document.getElementById('upperbody-atlas').textContent));
 let angle=config.initial,view='front',playing=false,phase=0,last=0,lastDraw=0,lastCapture=0;
 let saved=hubConfig?.state;try{saved??=JSON.parse(localStorage.getItem(store)||'null');}catch{}const content=saved?.modelContent;if(content?.topic===topic){if(Number.isFinite(content.angle))angle=Math.max(config.min,Math.min(config.max,content.angle));if(['front','side','back'].includes(content.camera))view=content.camera;if(typeof content.fibers==='boolean')by('fibers').checked=content.fibers;if(typeof content.transparent==='boolean')by('transparent').checked=content.transparent;playing=saved.privateContent?.playing===true&&!matchMedia('(prefers-reduced-motion: reduce)').matches;}
 function render(){if(!root.isConnected)return;root.classList.toggle('no-fibers',!by('fibers').checked);root.classList.toggle('transparent',by('transparent').checked);root.dataset.revision='native-upperbody-atlas-v2';root.dataset.angle=Math.round(angle);root.dataset.camera=view;model.render(angle,view);by('angle').value=Math.round(angle);const text=Math.round(angle)+'°';by('value').textContent=text;by('angle').setAttribute('aria-valuetext',text);for(const v of ['front','side','back'])by(v).setAttribute('aria-pressed',v===view);root.querySelector('.diagram-caption').textContent=(view==='side'?'측면':view==='front'?'정면':'후면')+' · 팔 외전 · 가슴·등·전거근';}
 function capture(){const state={modelContent:{revision:'native-upperbody-atlas-v2',topic,angle:Math.round(angle),camera:view,fibers:by('fibers').checked,transparent:by('transparent').checked},privateContent:{playing}};try{localStorage.setItem(store,JSON.stringify(state));}catch{}if(hubConfig)parent.postMessage({type:'anatomy-hub-state',key:hubConfig.key,state},'*');}
 function play(on){playing=on;by('play').textContent=on?'일시정지':'재생';by('play').setAttribute('aria-pressed',on);last=0;}
 function syncPhase(){phase=Math.acos(Math.max(-1,Math.min(1,1-2*(angle-config.min)/(config.max-config.min))));}
 by('angle').addEventListener('input',()=>{play(false);angle=+by('angle').value;render();capture();});by('play').addEventListener('click',()=>{if(!playing)syncPhase();play(!playing);capture();});for(const v of ['front','side','back'])by(v).addEventListener('click',()=>{view=v;render();capture();queueFit();});for(const id of ['fibers','transparent'])by(id).addEventListener('change',()=>{render();capture();queueFit();});
 let pending=false;function fit(){pending=false;if(!root.isConnected)return;const svg=root.querySelector('svg'),available=Math.max(0,document.documentElement.clientWidth-32),overhead=root.scrollHeight-svg.getBoundingClientRect().height,width=Math.floor(available<=680?available:Math.min(available,700,Math.max(220,(innerHeight-overhead-48)*870/Number(root.dataset.sceneHeight||540))))+'px';if(root.style.width!==width)root.style.width=width;}
 function queueFit(){if(!pending){pending=true;requestAnimationFrame(fit);}}window.addEventListener('resize',queueFit);new ResizeObserver(queueFit).observe(root);new ResizeObserver(render).observe(root);
 function tick(t){if(!root.isConnected)return;if(playing&&!document.hidden&&t-lastDraw>=85){if(last)phase+=Math.min(t-last,160)*Math.PI/5500;angle=config.min+(config.max-config.min)*(1-Math.cos(phase))/2;render();last=t;lastDraw=t;if(t-lastCapture>=500){capture();lastCapture=t;}}requestAnimationFrame(tick);}requestAnimationFrame(tick);
 window.nativeUpperbody={model,root,setPose(a,v=view){play(false);angle=Math.max(config.min,Math.min(config.max,a));if(['front','side','back'].includes(v))view=v;render();capture();}};syncPhase();play(playing);render();queueFit();capture();
})();
