function NativeUpperbodyRenderer(root,data){
 const motion=NativeUpperbodyMotion(data),colors={red:'#e02e2a',blue:'#339cff',green:'#00a240',orange:'#e25507',purple:'#924ff7',yellow:'#ffc300',teal:'#35b8b0'},ns='http://www.w3.org/2000/svg',svg=root.querySelector('svg'),defs=svg.querySelector('defs'),drawing=svg.querySelector('.native-volumes'),leaders=svg.querySelector('.native-labels');
 const specs={front:[['pectoral-clavicular','대흉근 쇄골부',24,175],['pectoral-sternal','대흉근 흉늑부',24,265],['pectoral-abdominal','대흉근 복부',24,340],['serratus','전거근',846,305]],back:[['trapezius-upper','승모근 상부',24,105],['trapezius-middle','승모근 중부',24,180],['trapezius-lower','승모근 하부',24,285],['latissimus','광배근',846,390],['infraspinatus','극하근',846,180],['teres-minor','소원근',846,120],['teres-major','대원근',846,255]],side:[['pectoral-sternal','대흉근',846,240],['serratus','전거근',846,335],['latissimus','광배근',24,395],['trapezius-upper','승모근',24,115],['infraspinatus','극하근',24,205],['teres-major','대원근',24,275]]};
 const make=(tag,attrs,parent)=>{const n=document.createElementNS(ns,tag);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,v));parent.append(n);return n;};
 const fasciaIds=new Map();data.parts.forEach((p,id)=>{if(p.tissuePatches)fasciaIds.set(id,data.parts.length+fasciaIds.size);});const ownerCount=data.parts.length+fasciaIds.size,isSoft=id=>id>=data.parts.length||data.parts[id].kind==='muscle';
 const nodes=data.parts.map((p,id)=>{const g=make('g',{'data-part':p.name,'data-kind':p.kind},drawing),clip=make('clipPath',{id:'upper-native-'+id},defs),mask=make('path',{},clip),fill=make('path',{fill:p.kind==='muscle'?colors[p.color]:p.kind==='cartilage'?'#fafafa':'#e8e9eb',stroke:'#89919e','stroke-width':p.kind==='muscle'?.6:.9,'stroke-opacity':p.kind==='muscle'?.45:.85},g),fiber=make('path',{class:'fiber',fill:'none',stroke:'var(--foreground)','stroke-width':.65,'stroke-opacity':.28,'clip-path':'url(#upper-native-'+id+')'},g);let fascia,fasciaMask,fasciaFiber;if(p.tissuePatches){const clip=make('clipPath',{id:'upper-fascia-'+id},defs);fasciaMask=make('path',{},clip);fascia=make('path',{'data-tissue':'aponeurosis',fill:'#f5f3ed',stroke:'none'},g);fasciaFiber=make('path',{class:'fiber',fill:'none',stroke:'#7f8390','stroke-width':.45,'stroke-opacity':.24,'clip-path':'url(#upper-fascia-'+id+')'},g);}return{g,fill,fiber,mask,fascia,fasciaMask,fasciaFiber};});
 for(const [id]of fasciaIds){const gradient=make('linearGradient',{id:'latissimus-volume-'+id,x1:'0%',y1:'0%',x2:'100%',y2:'0%'},defs);for(const [offset,color]of [['0%','#ab75f8'],['45%','#924ff7'],['100%','#7d43d2']])make('stop',{offset,'stop-color':color},gradient);nodes[id].fill.setAttribute('fill','url(#latissimus-volume-'+id+')');nodes[id].fiber.setAttribute('stroke-opacity','.36');}
 const labelNodes=new Map();for(const list of Object.values(specs))for(const [name,text]of list){if(labelNodes.has(name+text))continue;const g=make('g',{'data-label':text},leaders),line=make('path',{},g),label=make('text',{},g);label.textContent=text;labelNodes.set(name+text,{g,line,label});}
 const curve=ps=>{if(ps.length<3)return '';let d='M'+ps[0].join(',');for(let i=1;i<ps.length-1;i++)d+='Q'+ps[i].join(',')+' '+ps[i].map((v,j)=>(v+ps[i+1][j])/2).join(',');return d+'L'+ps.at(-1).join(',');};
 function clipNeck(ps){const result=[];for(let i=0;i<ps.length;i++){const a=ps[i],b=ps[(i+1)%ps.length],ina=a[1]>=data.neckTop,inb=b[1]>=data.neckTop;if(ina)result.push(a);if(ina!==inb){const t=(data.neckTop-a[1])/(b[1]-a[1]);result.push(a.map((v,j)=>v+(b[j]-v)*t));}}return result;}
 let lastKey='',lastAngle=null,posed,debug;
 function render(angle,view){
  angle=Math.round(angle);const transparent=root.classList.contains('transparent'),fibers=!root.classList.contains('no-fibers'),key=[angle,view,transparent,fibers,root.clientWidth].join();if(key===lastKey)return;lastKey=key;const start=performance.now();if(angle!==lastAngle){posed=motion.pose(angle);lastAngle=angle;}
  const scale=2.25,yaw=data.cameraYaw[['front','side','back'].indexOf(view)],a=yaw*Math.PI/180,c=Math.cos(a),s=Math.sin(a),project=p=>[435+(p[0]*c+p[2]*s)*scale,25+(p[1]-data.neckTop)*scale],depth=p=>-p[0]*s+p[2]*c,buffer=AbdominalVisibility({project,depth,step:1});
  const paint=(points,owner)=>{for(const [edge,sign]of [[8,1],[862,-1]]){const clipped=[];for(let i=0;i<points.length;i++){const a=points[i],b=points[(i+1)%points.length],x=project(a)[0],next=project(b)[0],inside=(x-edge)*sign>=0,other=(next-edge)*sign>=0;if(inside)clipped.push(a);if(inside!==other){const t=(edge-x)/(next-x);clipped.push(a.map((v,j)=>v+t*(b[j]-v)));}}points=clipped;}buffer.polygon(points,owner);};
  const allowed=p=>p.kind!=='muscle'||view==='side'||(view==='front'?(p.name.startsWith('pectoral')||p.name.startsWith('serratus')):!(p.name.startsWith('pectoral')||p.name.startsWith('serratus')));
  data.parts.forEach((p,id)=>{if(!allowed(p))return;if(p.tissuePatches){for(const [kind,patches]of Object.entries(p.tissuePatches))for(const patch of patches){const face=p.f[patch.face].map(index=>posed[id].v[index]);paint(patch.weights.map(weights=>[0,1,2].map(axis=>weights.reduce((sum,weight,j)=>sum+weight*face[j][axis],0))),kind==='muscle'?id:fasciaIds.get(id));}}else p.f.forEach(f=>{const face=f.map(i=>posed[id].v[i]);paint(p.name.startsWith('trapezius-upper')?clipNeck(face):face,id);});});
  const visible=buffer.solve(ownerCount,{projections:isSoft,scanlineClips:false,occludes:id=>!transparent||!isSoft(id)});
  nodes.forEach((n,id)=>{const p=data.parts[id],soft=p.kind==='muscle',local=visible.ownerZ[id],outline=AtlasContour(visible,k=>transparent&&soft?local[k]>-Infinity:visible.owners[k]===id,visible.bounds[id]);n.fill.setAttribute('d',outline);n.mask.setAttribute('d',outline);n.g.setAttribute('opacity',transparent&&soft?.3:1);let fiberPath='';
   let fasciaPath='';if(n.fascia){const owner=fasciaIds.get(id),local=visible.ownerZ[owner],outline=AtlasContour(visible,k=>transparent?local[k]>-Infinity:visible.owners[k]===owner,visible.bounds[owner]);n.fascia.setAttribute('d',outline);n.fasciaMask.setAttribute('d',outline);}
   if(soft&&fibers&&allowed(p))for(let index=0;index<posed[id].fibers.length;index++){const fiber=posed[id].fibers[index],fascia=p.surfaceGuides?.[index].kind==='aponeurosis',owner=fascia?fasciaIds.get(id):id,local=visible.ownerZ[owner];let segment=[];const flush=()=>{let length=0;for(let j=1;j<segment.length;j++)length+=Math.hypot(...segment[j].map((v,k)=>v-segment[j-1][k]));if(length>=5){if(fascia)fasciaPath+=curve(segment);else fiberPath+=curve(segment);}segment=[];};for(const q of fiber){const point=project(q),x=Math.floor((point[0]-visible.x0)/visible.step),y=Math.floor((point[1]-visible.y0)/visible.step),k=y*visible.w+x;if((!p.name.startsWith('trapezius-upper')||q[1]>=data.neckTop)&&x>=0&&x<visible.w&&y>=0&&y<visible.h&&depth(q)>=local[k]-2.5&&(transparent||visible.owners[k]===owner))segment.push(point);else flush();}flush();}n.fiber.setAttribute('d',fiberPath);if(n.fasciaFiber)n.fasciaFiber.setAttribute('d',fasciaPath);
  });
  labelNodes.forEach(n=>n.g.style.display='none');const shown=[];
  for(const [name,text,x,originalY]of specs[view]){const y=25+(originalY-25)*scale/1.04,ids=data.parts.map((p,id)=>p.name===name||p.name===name+'-right'?id:-1).filter(i=>i>=0).sort((a,b)=>visible.coverage[b]-visible.coverage[a]);let id=ids[0],points=visible.centers[id];if(transparent){id=ids.find(i=>visible.bounds[i][0]<=visible.bounds[i][2])??id;points=[];const b=visible.bounds[id];for(let y=b[1];y<=b[3];y+=8)for(let x=b[0];x<=b[2];x+=8)if(visible.ownerZ[id][y*visible.w+x]>-Infinity)points.push([visible.x0+x,visible.y0+y]);}if(points.length<3)continue;
   const mean=points.reduce((sum,p)=>sum.map((v,j)=>v+p[j]/points.length),[0,0]),target=points.reduce((best,p)=>Math.hypot(...p.map((v,j)=>v-mean[j]))<Math.hypot(...best.map((v,j)=>v-mean[j]))?p:best),n=labelNodes.get(name+text);n.g.style.display='';n.label.setAttribute('x',x);n.label.setAttribute('y',y);n.label.setAttribute('text-anchor',x<435?'start':'end');n.line.setAttribute('d',`M${x},${y+5}L${target.join(',')}`);shown.push({text,color:colors[data.parts[id].color]});
  }
  const legend=root.querySelector('.diagram-legend');legend.replaceChildren();for(const item of shown){const span=document.createElement('span'),key=document.createElement('i');key.style.background=item.color;span.append(key,document.createTextNode(item.text));legend.append(span);}
  const top=Math.min(0,...data.parts.flatMap((p,id)=>['humerus','radius','ulna'].includes(p.name.replace(/-right$/,''))?posed[id].v.filter(q=>{const x=project(q)[0];return x>=8&&x<=862;}).map(q=>project(q)[1]-15):[])),bottom=25+(500-data.neckTop)*scale+35;svg.setAttribute('viewBox',`0 ${top} 870 ${bottom-top}`);root.dataset.sceneWidth=870;root.dataset.sceneHeight=bottom-top;svg.style.height='auto';svg.removeAttribute('height');labelNodes.forEach(n=>n.label.style.fontSize=(11*870/Math.max(1,root.clientWidth))+'px');root.dataset.cameraYaw=yaw;debug={angle,view,duration:performance.now()-start,labels:shown.map(p=>p.text),coverage:visible.coverage};
 }
 return{render,motion,data,get debug(){return debug;}};
}
